AWSTemplateFormatVersion: "2010-09-09"
Resources:
  myEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      KeyName: mykey
      ImageId: ami-0599b6e53ca798bb2
      InstanceType: t2.micro
      Monitoring: false
      SecurityGroupIds:
        - !ImportValue SG1Name #pubulic
      SubnetId: !ImportValue Subnet1Name #pubulic
      Tags:
        - Key: Name
          Value: CFec2

  myPrivateEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      KeyName: mykey
      ImageId: ami-0599b6e53ca798bb2
      InstanceType: t2.micro
      Monitoring: false
      SecurityGroupIds:
        - !ImportValue SG2Name # private
      SubnetId: !ImportValue PrivateSubnetId # private
      Tags:
        - Key: Name
          Value: PrivateCFec2    